### ISSUE TITLE
No code completion win/mac

### ISSUE THREAD

**Issue by ghost** [jgranick/md-haxebinding#11]
I have updated addin from addins manager. All those errors are gone (when trying to trigger code completion), but unfortunately there's no code completion at all.

It doesn't work on write mode(triggered by letters) nor ctrl + space.

Tried on win7 32 bit and MacOS Lion:
- haxe 2.08
- latest mono develop
- latest mono

**Comment by DanielUranga** [comment]
I confirm the Issue on Mac Os X, with Haxe 2.09 and the latest dll pulled from the git repo. Everything is ok except for the code completion dialogs, they just disappeared.

**Comment by andyli** [comment]
It was not working 2 days ago, but now it works perfectly for me.
I'm using haxe r4473, monodevelop haxe binding 0.2.1, on Mac 10.7.3.

**Comment by jgranick** [comment]
Bear in mind, the add-in uses Haxe compiler completion right now. It doesn't implement the full (and much more complicated) parser from FlashDevelop.

It works well but it only provides completion on a period or parenthesis. As a result, "this.graphics" will provide completion, but "graphics" will not. There may be some hacks/workarounds I could do to make that work

**Comment by matthewswallace** [comment]
Would be great to have code complete by hitting a keyboard shortcut like in FDT or Flashbuilder  "Spacebar > Control" on the Mac.

Also is it possible to get automatic imports ?

**Comment by blurmonk** [comment]
Hi
I can confirm that code completion does not work on MD 3.0.3.4 haxe 2.10, 0.3.1 binding under Win7 64

**Comment by rynti** [comment]
I'm not sure but this may be fixed with #19, I guess you had spaces in at least one of your classpaths.
