### ISSUE TITLE
Monodevelop/Sublime Text 2 Autocomplete Crash

### ISSUE THREAD

**Issue by Kamek** [jgranick/md-haxebinding#15]
Just installed SLT2, haxe, and nme fresh on my newish MBP. Now both monodevelop and SLT2 both crash when just before an autocomplete comes up. Here's the Console.app crash report : git://gist.github.com/3278256.git
anyone have the same problem?

**Comment by jgranick** [comment]
Are you still having this problem?

**Comment by Kamek** [comment]
No sorry, I downgraded to Snow Leopard and all seems to be well now. I'm not sure what the problem was but I can't reproduce it so we can close this issue.
