### ISSUE TITLE
Auto import like in C#

### ISSUE THREAD

**Issue by JbIPS** [jgranick/md-haxebinding#23]
One thing I loved in FD was that I no longer managed imports. With some google searchs, I saw that MonoDevelop has the same tools to do that, but I didn't worked with NME project.

If you can just point me the direction to enable this, I'll fork it.

And for all that work, thanks a lot !

**Comment by atomicptr** [comment]
This probably refers to #10

**Comment by JbIPS** [comment]
Yes, it's just a small part of the #10, I don't know if it's independent or
not.
