### ISSUE TITLE
(Windows) MonoDevelop (2.8.8.4) freezes when creating new NME solution

### ISSUE THREAD

**Issue by ghost** [jgranick/md-haxebinding#7]
MonoDevelop freezes and finally crashes( every time ) with 'not responding' dialog when creating new NME solution (Empty NME project template) .

MonoDevelop 2.8.8.4, win 7 32 bit

**Comment by jgranick** [comment]
Does this still occur?

**Comment by ghost** [comment]
It creates the NME solution after some time waiting (about 30secs on a quad core machine).
Tested it on win7 32bt and MacOS Lion.

While creating solution on windows it blocks the UI with not responding message in the form title bar but
after ~30sec wait it finally creates the solution.

Building simple trace("foo") solution works ( html target ) but no code completion (posted as new issue).

**Comment by andyli** [comment]
It is also affecting me on my Mac 10.7, using MonoDevelop 3.0.3.4, Haxe Language Binding 0.3.1.

**Comment by ghost** [comment]
Try waiting a little bit longer. It takes some time unfortunately. At least for me.

**Comment by andyli** [comment]
Yes it does create the project after some time.
What I meant is it also freezes for several sounds when creating project.
And I believe it shouldn't have take that long.

**Comment by jgranick** [comment]
I'm not sure why this happens.

I'll try and profile it and figure it out

------Original Message------

**Comment by MatthieuChardon** [comment]
I've the same issue, even with the "Run as administrator" option. But for me, it never creates a valid project. All what i get is an empty folder : "Assets".

Windows 7 64bit, MonoDevelop 3.0.3.5, Haxe Language Binding 0.3.6.

EDIT : Finally, it succeeded ! I just restarted my PC. Now, i just have to wait something like 30sec.

**Comment by jgranick** [comment]
I cannot reproduce this problem using the current alpha. I'm not sure if this was because of the move to a standard "project.nmml" file, or if this was an error that was corrected within the IDE, but I believe this is resolved.
