### ISSUE TITLE
Error while executing command: Show Completion Window

### ISSUE THREAD

**Issue by wselken** [jgranick/md-haxebinding#9]
Any ideas?
Error: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.HaxeBinding.Languages.Gui.HaxeTextEditorCompletion.FetchCompletionData (MonoDevelop.Ide.CodeCompletion.CodeCompletionContext completionContext) [0x00000] in <filename unknown>:0 
  at MonoDevelop.HaxeBinding.Languages.Gui.HaxeTextEditorCompletion.GetCompletionList (MonoDevelop.Ide.CodeCompletion.CodeCompletionContext completionContext) [0x00000] in <filename unknown>:0 
  at MonoDevelop.HaxeBinding.Languages.Gui.HaxeTextEditorCompletion.HandleCodeCompletion (MonoDevelop.Ide.CodeCompletion.CodeCompletionContext completionContext, Char completionChar) [0x00000] in <filename unknown>:0 
  at MonoDevelop.Ide.Gui.Content.CompletionTextEditorExtension.CodeCompletionCommand (MonoDevelop.Ide.CodeCompletion.CodeCompletionContext completionContext) [0x00000] in <filename unknown>:0 
  at MonoDevelop.Ide.Gui.Content.CompletionTextEditorExtension.RunCompletionCommand () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at MonoDevelop.Components.Commands.CommandHandlerInfo.Run (System.Object cmdTarget, MonoDevelop.Components.Commands.Command cmd) [0x00000] in <filename unknown>:0 
  at MonoDevelop.Components.Commands.CommandManager+<DispatchCommand>c__AnonStorey42.<>m__57 () [0x00000] in <filename unknown>:0 
  at MonoDevelop.Components.Commands.CommandManager.DispatchCommand (System.Object commandId, System.Object dataItem, System.Object initialTarget, CommandSource source) [0x00000] in <filename unknown>:0 

Using Kubuntu 12.04

Version
MonoDevelop 2.8.6.3
Installation UUID: 1561ee72-02de-4a17-8154-d34adfc2f640
Runtime:
    Mono 2.10.8.1 (Debian 2.10.8.1-1ubuntu2)
    GTK 2.24.10
    GTK# (2.12.0.0)
Build information:
    Git revision: f4289daf57621f5593ad5bf78b3ff5ad878e3c7a-dirty
    Build date: 2012-02-20 07:20:06+0000
Operating System:
    Linux
    Linux 28desktop 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:41:14 UTC 2012 i686 i686 i386 GNU/Linux
Loaded assemblies:
MonoDevelop.RegexToolkit             2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.RegexToolkit/MonoDevelop.RegexToolkit.dll
ILAsmBinding                         2.6.0.0        /usr/lib/monodevelop/AddIns/BackendBindings/ILAsmBinding.dll
OldNRefactory                        2.1.1.0        /usr/lib/monodevelop/bin/OldNRefactory.dll
gconf-sharp                          2.24.0.0       /usr/lib/mono/gac/gconf-sharp/2.24.0.0__35e10195dab3c99f/gconf-sharp.dll
MonoDevelop.HexEditor                2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.HexEditor.dll
MonoDevelop.AssemblyBrowser          2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.AssemblyBrowser.dll
ICSharpCode.NRefactory               1.0.4433.13142 /usr/lib/monodevelop/bin/ICSharpCode.NRefactory.dll
MonoDevelop.HaxeBinding              1.0.4484.31754 /usr/lib/monodevelop/AddIns/MonoDevelop.HaxeBinding.dll
MonoDevelop.Projects.Formats.MSBuild 1.0.0.0        /usr/lib/monodevelop/bin/MonoDevelop.Projects.Formats.MSBuild.exe
MonoDevelop.MsVisualStudio           2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.MsVisualStudio/MonoDevelop.MsVisualStudio.dll
MonoDevelop.VBNetBinding             2.6.0.0        /usr/lib/monodevelop/AddIns/BackendBindings/MonoDevelop.VBNetBinding.dll
MonoDevelop.CSharpBinding            2.6.0.0        /usr/lib/monodevelop/AddIns/BackendBindings/MonoDevelop.CSharpBinding.dll
I18N.Rare                            4.0.0.0        /usr/lib/mono/gac/I18N.Rare/4.0.0.0__0738eb9f132ed756/I18N.Rare.dll
I18N.CJK                             4.0.0.0        /usr/lib/mono/gac/I18N.CJK/4.0.0.0__0738eb9f132ed756/I18N.CJK.dll
I18N.MidEast                         4.0.0.0        /usr/lib/mono/gac/I18N.MidEast/4.0.0.0__0738eb9f132ed756/I18N.MidEast.dll
I18N.Other                           4.0.0.0        /usr/lib/mono/gac/I18N.Other/4.0.0.0__0738eb9f132ed756/I18N.Other.dll
I18N.West                            4.0.0.0        /usr/lib/mono/gac/I18N.West/4.0.0.0__0738eb9f132ed756/I18N.West.dll
I18N                                 4.0.0.0        /usr/lib/mono/gac/I18N/4.0.0.0__0738eb9f132ed756/I18N.dll
MonoDevelop.CodeMetrics              2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.CodeMetrics/MonoDevelop.CodeMetrics.dll
MonoDevelop.CBinding                 2.6.0.0        /usr/lib/monodevelop/AddIns/BackendBindings/MonoDevelop.CBinding.dll
MonoDevelop.Refactoring              2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.Refactoring/MonoDevelop.Refactoring.dll
MonoDevelop.AspNet.Mvc               2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.AspNet.Mvc/MonoDevelop.AspNet.Mvc.dll
MonoDevelop.TextTemplating           2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/MonoDevelop.TextTemplating.dll
Mono.TextTemplating                  0.0.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/Mono.TextTemplating.dll
MonoDevelop.WebReferences            2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.WebReferences/MonoDevelop.WebReferences.dll
MonoDevelop.AspNet                   2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.AspNet/MonoDevelop.AspNet.dll
MonoDevelop.XmlEditor                2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.XmlEditor/MonoDevelop.XmlEditor.dll
MonoDevelop.SourceEditor2            2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.SourceEditor2.dll
MonoDevelop.Gettext                  2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.Gettext/MonoDevelop.Gettext.dll
MonoDevelop.Autotools                2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.Autotools/MonoDevelop.Autotools.dll
ICSharpCode.SharpZipLib              2.84.0.0       /usr/lib/mono/gac/ICSharpCode.SharpZipLib/2.84.0.0__1b03e6acf1164f73/ICSharpCode.SharpZipLib.dll
Mono.Security                        4.0.0.0        /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll
MonoDevelop.Deployment.Linux         2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.Deployment/MonoDevelop.Deployment.Linux.dll
MonoDevelop.Deployment               2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.Deployment/MonoDevelop.Deployment.dll
MonoDevelop.GtkCore                  2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.GtkCore/MonoDevelop.GtkCore.dll
libsteticui                          0.0.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.GtkCore/libsteticui.dll
libstetic                            0.0.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.GtkCore/libstetic.dll
MonoDevelop.DesignerSupport          2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.dll
Mono.Debugging                       0.0.0.0        /usr/lib/monodevelop/bin/Mono.Debugging.dll
MonoDevelop.Debugger                 2.6.0.0        /usr/lib/monodevelop/AddIns/MonoDevelop.Debugger/MonoDevelop.Debugger.dll
pango-sharp                          2.12.0.0       /usr/lib/mono/gac/pango-sharp/2.12.0.0__35e10195dab3c99f/pango-sharp.dll
monodoc                              1.0.0.0        /usr/lib/mono/gac/monodoc/1.0.0.0__0738eb9f132ed756/monodoc.dll
System.Drawing                       4.0.0.0        /usr/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
Mono.Cecil                           0.9.4.0        /usr/lib/monodevelop/bin/Mono.Cecil.dll
gnome-vfs-sharp                      2.24.0.0       /usr/lib/mono/gac/gnome-vfs-sharp/2.24.0.0__35e10195dab3c99f/gnome-vfs-sharp.dll
gnome-sharp                          2.24.0.0       /usr/lib/mono/gac/gnome-sharp/2.24.0.0__35e10195dab3c99f/gnome-sharp.dll
GnomePlatform                        2.6.0.0        /usr/lib/monodevelop/AddIns/GnomePlatform/GnomePlatform.dll
System.Configuration                 4.0.0.0        /usr/lib/mono/gac/System.Configuration/4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
Mono.Cairo                           4.0.0.0        /usr/lib/mono/gac/Mono.Cairo/4.0.0.0__0738eb9f132ed756/Mono.Cairo.dll
gdk-sharp                            2.12.0.0       /usr/lib/mono/gac/gdk-sharp/2.12.0.0__35e10195dab3c99f/gdk-sharp.dll
Mono.TextEditor                      1.0.0.0        /usr/lib/monodevelop/bin/Mono.TextEditor.dll
atk-sharp                            2.12.0.0       /usr/lib/mono/gac/atk-sharp/2.12.0.0__35e10195dab3c99f/atk-sharp.dll
glib-sharp                           2.12.0.0       /usr/lib/mono/gac/glib-sharp/2.12.0.0__35e10195dab3c99f/glib-sharp.dll
gtk-sharp                            2.12.0.0       /usr/lib/mono/gac/gtk-sharp/2.12.0.0__35e10195dab3c99f/gtk-sharp.dll
Mono.Posix                           4.0.0.0        /usr/lib/mono/gac/Mono.Posix/4.0.0.0__0738eb9f132ed756/Mono.Posix.dll
Mono.Addins                          0.6.0.0        /usr/lib/mono/gac/Mono.Addins/0.6.0.0__0738eb9f132ed756/Mono.Addins.dll
Mono.Addins.Setup                    0.6.0.0        /usr/lib/mono/gac/Mono.Addins.Setup/0.6.0.0__0738eb9f132ed756/Mono.Addins.Setup.dll
System.Xml                           4.0.0.0        /usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll
System.Xml.Linq                      4.0.0.0        /usr/lib/mono/gac/System.Xml.Linq/4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
System.Core                          4.0.0.0        /usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll
System                               4.0.0.0        /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
MonoDevelop.Core                     2.6.0.0        /usr/lib/monodevelop/bin/MonoDevelop.Core.dll
MonoDevelop.Ide                      2.6.0.0        /usr/lib/monodevelop/bin/MonoDevelop.Ide.dll
MonoDevelop                          2.6.0.0        /usr/lib/monodevelop/bin/MonoDevelop.exe
mscorlib                             4.0.0.0        /usr/lib/mono/4.0/mscorlib.dll

**Comment by jgranick** [comment]
I just made an update which should help resolve null issues when performing code completion. Would you mind updating to the latest version and giving it a try?

Thanks!

**Comment by wselken** [comment]
it doesn't blow up anymore.  However, I'm not seeing the code completion window.  has this feature not completed, or do i need to do something to configure this?

**Comment by wselken** [comment]
okay, i figured it out.  I was using an old nme verision. And this tool requires 3.2 or higher, due to the new 'display' command used. (maybe 3.3.0, since i pulled latest to fix the issue) You might want to note that on front page or somewhere. (if you haven't already, i didn't see it anywhere).
